global using Carter;
global using FluentValidation;
global using FluentValidation.Results;
global using Mapster;
global using Marten;
global using MediatR;
global using BuildingBlocks.CQRS;
global using Catalog.API.Models;
global using Catalog.API.Exceptions;
